SET SCHEMA `MICROSERVICE`;

DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `FILE`;

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `FILE` (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    EXTENSION VARCHAR(255) NOT NULL,
    FILEDATA BLOB,
    NAME VARCHAR(255) NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    CUSTOMERID BIGINT NOT NULL
);