#!/usr/bin/env bash

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
#                   Set H2 database settings
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

export H2_TCP_PORT=9092
export H2_WEB_PORT=8082
export H2_HOME=/h2db
export H2_DB=msdb
export H2_DRIVER=org.h2.Driver
export H2_URL="jdbc:h2:tcp://127.0.0.1:$H2_TCP_PORT/$H2_HOME/$H2_DB;CIPHER=AES"
export H2_USER=admin
export H2_CIPHER=filepa55
export H2_PASS=schemapa55
export H2_SEC="$H2_CIPHER $H2_PASS"
export H2_PID=`netstat -anltup 2>/dev/null | grep -w :::$H2_TCP_PORT | awk '{print $7}' | grep -o '[0-9]*'`
export H2_WEB_CONSOLE_PID=`netstat -anltup 2>/dev/null | grep -w :::$H2_WEB_PORT= | awk '{print $7}' | grep -o '[0-9]*'`