DROP TABLE IF EXISTS MICROSERVICE.CUSTOMER;
DROP TABLE IF EXISTS MICROSERVICE.FILE;

CREATE TABLE IF NOT EXISTS MICROSERVICE.CUSTOMER (
    ID BIGINT DEFAULT NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL
);

INSERT INTO MICROSERVICE.CUSTOMER(ID, FIRSTNAME, LASTNAME) VALUES
(1, 'Joe', 'Bloggs'),
(2, 'Alice', 'Doe'),
(3, 'Harry', 'Wizard');

CREATE TABLE IF NOT EXISTS MICROSERVICE.FILE (
    ID BIGINT DEFAULT NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    EXTENSION VARCHAR(255) NOT NULL,
    FILEDATA BLOB,
    NAME VARCHAR(255) NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    CUSTOMERID BIGINT NOT NULL
);